name: Pipeline de CI/CD para Aplicación Spring Boot en EC2 con Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project files to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<'EOF'
          cd /home/ubuntu/classcraft
          git fetch --all
          git reset --hard origin/main
          docker-compose down
          docker-compose up -d --build
          EOF
        shell: bash
